name: CI

on: 
  push:
    branches: [master]
  
  
env:
  DEPLOY_PATH: /var/www/app
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки
      # Чтобы избежать конфиликтов с URL, меняем точки на _, а слеши на минусы
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_REMOTE_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/${{ secrets.DOMAIN }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at https://${{ secrets.DOMAIN }}"
